@startuml

title info.exe
'hide footbox

control Yubikey
control info.exe    

info.exe -> Yubikey: hid_open_path()
|||
|||
info.exe -> Yubikey: CTAPHID_INIT (0x06)
info.exe <-- Yubikey: Response
note over info.exe:出力\n proto: 0x02\n major:0x05\n minor:0x00\n build:0x02\n caps: 0x05 (wink, cbor, msg)
|||
|||
info.exe -> Yubikey: CTAPHID_CBOR (0x10) - authenticatorGetInfo (0x04)
info.exe <-- Yubikey: Response
note over info.exe:出力\n version strings: U2F_V2, FIDO_2_0\n extension strings: hmac-secret\n aaguid: xxx\n options: rk, up, noplat, noclientPin\n maxmsgsiz: 1200\n pin protocols: 1
|||
|||
info.exe -> Yubikey: hid_close()

@enduml
